openapi: 3.0.0
info:
  title: Syrup API
  description: A standardized interface for coupon code providers to integrate with the Syrup browser extension. Please also see the API documentation markdown file for more information.
  version: 1.0.0
servers:
  - url: https://api.provider.com/syrup
    description: Example server
paths:
  /version:
    get:
      summary: Get API Version
      description: Returns information about the API implementation
      operationId: getVersion
      responses:
        '200':
          description: Successful response
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests allowed per time window
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: The number of requests remaining in the time window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: The time when the rate limit window resets (Unix timestamp)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-RetryAfter:
              description: Time to wait before retrying (seconds)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /coupons:
    get:
      summary: List Coupons
      description: Returns a paginated list of coupons for a specific domain
      operationId: listCoupons
      parameters:
        - name: domain
          in: query
          description: The website domain to fetch coupons for
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of coupons to return
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Number of coupons to skip
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests allowed per time window
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: The number of requests remaining in the time window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: The time when the rate limit window resets (Unix timestamp)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-RetryAfter:
              description: Time to wait before retrying (seconds)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /coupons/valid/{id}:
    post:
      summary: Report Valid Coupon
      description: Report that a coupon code was successfully used
      operationId: reportValidCoupon
      parameters:
        - name: id
          in: path
          description: The ID of the coupon
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests allowed per time window
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: The number of requests remaining in the time window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: The time when the rate limit window resets (Unix timestamp)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-RetryAfter:
              description: Time to wait before retrying (seconds)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /coupons/invalid/{id}:
    post:
      summary: Report Invalid Coupon
      description: Report that a coupon code failed to work
      operationId: reportInvalidCoupon
      parameters:
        - name: id
          in: path
          description: The ID of the coupon
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests allowed per time window
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: The number of requests remaining in the time window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: The time when the rate limit window resets (Unix timestamp)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-RetryAfter:
              description: Time to wait before retrying (seconds)
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Coupon:
      type: object
      required:
        - id
        - title
        - description
        - code
        - score
        - merchant_name
      properties:
        id:
          type: string
          description: Unique identifier for the coupon
        title:
          type: string
          description: Display title with discount amount
        description:
          type: string
          description: Detailed coupon information
        code:
          type: string
          description: The actual coupon code
        score:
          type: number
          description: Relevance/reliability score
        merchant_name:
          type: string
          description: Store/website name
    CouponList:
      type: object
      required:
        - coupons
        - total
      properties:
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/Coupon'
        total:
          type: integer
          description: Total number of coupons available
    VersionInfo:
      type: object
      required:
        - version
        - provider
      properties:
        version:
          type: string
          description: API version (semantic versioning recommended)
        provider:
          type: string
          description: Provider's name or identifier
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Detailed error message
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Syrup-API-Key
      description: Optional API key for authentication
security:
  - ApiKeyAuth: []
